4236-Add CRA scanning to skit monitoring pipelines
IBM/devex-skit-monitor-toolchain pull request #33
Opened 2021-06-09 19:04 UTC by TBolton2000

A few changes were needed to allow for CRA scanning to run on the skit monitoring pipelines:

- Add cra from tekton-catalog to pipeline definitions for both cf and helm
- Add DevOps Insight tile to the toolchain
- Read APP_NAME (for CF) and app-name (for helm) into props skit-name in order to get the repo name after cloning
- Added props pr-url, scm-type, and project-id and gave them defaults for cra task inputs

2021-06-09 19:58 UTC, gee4vee approved these changes

2021-06-10 13:37 UTC, nfstein requested changes

2021-06-10 13:37 UTC, nfstein commented on .pipeline/helm/pipeline.yaml
>      - name: docker-lint
following stages need to "runAfter" these. You should add cra-cis-check, code-vulnerability-scan, and cra-bom to the runAfter for the build stage. Otherwise we could potentially notify the slack channels etc that everything is good when these tasks would fail.

2021-06-10 19:10 UTC, nfstein approved these changes

2021-06-10 19:11 UTC, merged